<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>NINA.Plugin.SessionCapture</AssemblyName>
    <RootNamespace>NINA.Plugin.SessionCapture</RootNamespace>
    <Platforms>x64</Platforms>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NINA.Plugin" Version="3.2.0.9001" />
  </ItemGroup>
</Project>
