using System.Reflection;
using System.Runtime.InteropServices;

[assembly: Guid("682531D1-5A23-4627-B961-0794282ECB4E")]
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: AssemblyTitle("Night Summary")]
[assembly: AssemblyDescription("Logs imaging session data and emails a summary report at sequence completion")]
[assembly: AssemblyCompany("Evan Pegors")]
[assembly: AssemblyProduct("Night Summary")]
[assembly: AssemblyCopyright("Copyright © 2026 Evan Pegors")]
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.0.0.2017")]
[assembly: AssemblyMetadata("License", "MPL-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.mozilla.org/en-US/MPL/2.0/")]
[assembly: AssemblyMetadata("Repository", "")]
[assembly: AssemblyMetadata("Homepage", "")]
[assembly: AssemblyMetadata("Tags", "report,summary,email,logging")]
[assembly: AssemblyMetadata("ChangelogURL", "")]
[assembly: AssemblyMetadata("FeaturedImageURL", "https://i.imgur.com/uvcC1dC.png")]
[assembly: AssemblyMetadata("ScreenshotURL", "")]
[assembly: AssemblyMetadata("AltScreenshotURL", "")]
[assembly: AssemblyMetadata("LongDescription", @"Night Summary captures imaging session data during sequence execution and sends an email report upon completion.")]
[assembly: ComVisible(false)]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]