using NINA.Plugin.NightSummary.Data;
using NINA.Plugin.NightSummary.Reporting;
using NINA.Plugin.NightSummary.Tests.Fixtures;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Xunit;

namespace NINA.Plugin.NightSummary.Tests {
    /// <summary>
    /// Tests for DiscordSender.BuildReportPayload — the pure-logic portion
    /// that assembles the Discord embed structure from report data.
    /// HTTP send paths are not tested here (require live webhooks).
    /// </summary>
    public class DiscordSenderTests {

        private readonly DiscordSender _sender = new DiscordSender("https://discord.com/api/webhooks/test/test");

        // ── Helpers ──────────────────────────────────────────────────────────

        /// <summary>
        /// Serialise the anonymous payload to JSON so we can make string assertions
        /// without relying on reflection to navigate the anonymous object graph.
        /// </summary>
        private static string ToJson(object payload) =>
            JsonSerializer.Serialize(payload);

        private static string PayloadJson(ReportData data) {
            var sender = new DiscordSender("https://discord.com/api/webhooks/test/test");
            return ToJson(sender.BuildReportPayload(data));
        }

        // ── Payload structure ─────────────────────────────────────────────────

        [Fact]
        public void Payload_ContainsUsername_NightSummary() {
            var json = PayloadJson(TestDataFactory.MakeReportData());
            Assert.Contains("Night Summary", json);
        }

        [Fact]
        public void Payload_ContainsEmbedsArray() {
            var json = PayloadJson(TestDataFactory.MakeReportData());
            Assert.Contains("embeds", json);
        }

        [Fact]
        public void Payload_ContainsFooterText() {
            var json = PayloadJson(TestDataFactory.MakeReportData());
            Assert.Contains("Generated by Night Summary", json);
        }

        [Fact]
        public void Payload_ContainsTimestamp() {
            var data = TestDataFactory.MakeReportData();
            var json = PayloadJson(data);
            // Timestamp is ISO-8601 UTC — spot check for 'Z' suffix
            Assert.Contains("Z", json);
        }

        // ── Session Overview field ────────────────────────────────────────────

        [Fact]
        public void Payload_SessionOverview_ContainsTotalImages() {
            var data = TestDataFactory.MakeReportData(imageCount: 10);
            var json = PayloadJson(data);
            Assert.Contains("Total Images: 10", json);
        }

        [Fact]
        public void Payload_SessionOverview_ContainsTotalExposure() {
            var data = TestDataFactory.MakeReportData(imageCount: 12);
            // 12 images × 300s each = 3600s = 1.0h
            var json = PayloadJson(data);
            Assert.Contains("Total Exposure: 1.0h", json);
        }

        [Fact]
        public void Payload_SessionOverview_ContainsAbortedNote_WhenSkippedExposures() {
            var data = TestDataFactory.MakeReportData(imageCount: 10, skippedExp: 3);
            var json = PayloadJson(data);
            Assert.Contains("3 aborted", json);
        }

        [Fact]
        public void Payload_SessionOverview_NoAbortedNote_WhenZeroSkipped() {
            var data = TestDataFactory.MakeReportData(imageCount: 10, skippedExp: 0);
            var json = PayloadJson(data);
            Assert.DoesNotContain("aborted", json);
        }

        [Fact]
        public void Payload_SessionOverview_ContainsAvgHFR_WhenImagesHaveHFR() {
            var data = TestDataFactory.MakeReportData(imageCount: 4);
            var json = PayloadJson(data);
            Assert.Contains("Avg HFR", json);
        }

        [Fact]
        public void Payload_SessionOverview_NoAvgHFR_WhenAllHFRZero() {
            var sessionId = Guid.NewGuid().ToString();
            var session   = TestDataFactory.MakeSession(sessionId);
            var images    = Enumerable.Range(0, 5)
                                      .Select(_ => TestDataFactory.MakeImage(sessionId, hfr: 0))
                                      .ToList();
            var data = new ReportData {
                Session = session, Images = images, Events = new List<SessionEvent>(),
                TsData  = new List<TsTargetData>(),
                CumulativeIntegrationSeconds = new Dictionary<string, double>(),
                SessionHistory = new Dictionary<string, List<TargetSessionHistory>>()
            };
            var json = PayloadJson(data);
            Assert.DoesNotContain("Avg HFR", json);
        }

        [Fact]
        public void Payload_SessionOverview_ContainsYield() {
            var data = TestDataFactory.MakeReportData(imageCount: 10);
            var json = PayloadJson(data);
            Assert.Contains("Yield:", json);
        }

        // ── Empty images ──────────────────────────────────────────────────────

        [Fact]
        public void Payload_EmptyImages_ContainsNoImagesMessage() {
            var sessionId = Guid.NewGuid().ToString();
            var session   = TestDataFactory.MakeSession(sessionId);
            var data = new ReportData {
                Session = session, Images = new List<ImageRecord>(),
                Events  = new List<SessionEvent>(),
                TsData  = new List<TsTargetData>(),
                CumulativeIntegrationSeconds = new Dictionary<string, double>(),
                SessionHistory = new Dictionary<string, List<TargetSessionHistory>>()
            };
            var json = PayloadJson(data);
            Assert.Contains("No images recorded", json);
        }

        [Fact]
        public void Payload_EmptyImages_DoesNotContainTargetFields() {
            var sessionId = Guid.NewGuid().ToString();
            var session   = TestDataFactory.MakeSession(sessionId);
            var data = new ReportData {
                Session = session, Images = new List<ImageRecord>(),
                Events  = new List<SessionEvent>(),
                TsData  = new List<TsTargetData>(),
                CumulativeIntegrationSeconds = new Dictionary<string, double>(),
                SessionHistory = new Dictionary<string, List<TargetSessionHistory>>()
            };
            var json = PayloadJson(data);
            Assert.DoesNotContain("HFR", json);
        }

        // ── Per-target breakdown ──────────────────────────────────────────────

        [Fact]
        public void Payload_SingleTarget_ContainsTargetName() {
            var data = TestDataFactory.MakeReportData(imageCount: 6, targets: new[] { "M31" });
            var json = PayloadJson(data);
            Assert.Contains("M31", json);
        }

        [Fact]
        public void Payload_MultipleTargets_ContainsAllTargetNames() {
            var data = TestDataFactory.MakeReportData(imageCount: 6,
                targets: new[] { "M31", "M42" });
            var json = PayloadJson(data);
            Assert.Contains("M31", json);
            Assert.Contains("M42", json);
        }

        [Fact]
        public void Payload_Target_ContainsTotalExposureLine() {
            var data = TestDataFactory.MakeReportData(imageCount: 6, targets: new[] { "M31" });
            var json = PayloadJson(data);
            Assert.Contains("Total:", json);
        }

        [Fact]
        public void Payload_Target_ContainsStarCountCV() {
            var data = TestDataFactory.MakeReportData(imageCount: 6, targets: new[] { "M31" });
            var json = PayloadJson(data);
            Assert.Contains("Star count CV", json);
        }

        // ── Image quality fields ──────────────────────────────────────────────

        [Fact]
        public void Payload_ContainsHFRField_WhenDataPresent() {
            var data = TestDataFactory.MakeReportData(imageCount: 6);
            var json = PayloadJson(data);
            // HFR appears both in overview ("Avg HFR") and as a standalone field
            Assert.Contains("\"HFR\"", json);
        }

        [Fact]
        public void Payload_ContainsFWHMField_WhenDataPresent() {
            var data = TestDataFactory.MakeReportData(imageCount: 6);
            var json = PayloadJson(data);
            Assert.Contains("\"FWHM\"", json);
        }

        [Fact]
        public void Payload_ContainsEccentricityField_WhenDataPresent() {
            var data = TestDataFactory.MakeReportData(imageCount: 6);
            var json = PayloadJson(data);
            Assert.Contains("Eccentricity", json);
        }

        [Fact]
        public void Payload_ContainsGuidingField_WhenDataPresent() {
            var data = TestDataFactory.MakeReportData(imageCount: 6);
            var json = PayloadJson(data);
            Assert.Contains("Guiding RMS", json);
        }

        [Fact]
        public void Payload_NoGuidingField_WhenAllGuidingZero() {
            var sessionId = Guid.NewGuid().ToString();
            var session   = TestDataFactory.MakeSession(sessionId);
            var images    = Enumerable.Range(0, 5)
                                      .Select(i => {
                                          var img = TestDataFactory.MakeImage(sessionId);
                                          img.GuidingRMSTotal = 0;
                                          return img;
                                      }).ToList();
            var data = new ReportData {
                Session = session, Images = images, Events = new List<SessionEvent>(),
                TsData  = new List<TsTargetData>(),
                CumulativeIntegrationSeconds = new Dictionary<string, double>(),
                SessionHistory = new Dictionary<string, List<TargetSessionHistory>>()
            };
            var json = PayloadJson(data);
            Assert.DoesNotContain("Guiding RMS", json);
        }

        [Fact]
        public void Payload_HFRField_ContainsMinMaxMeanCV() {
            var data = TestDataFactory.MakeReportData(imageCount: 6);
            var json = PayloadJson(data);
            Assert.Contains("Min", json);
            Assert.Contains("Max", json);
            Assert.Contains("Mean", json);
            Assert.Contains("CV", json);
        }
    }
}
