namespace NINA.Plugin.NightSummary.Dashboard.WebAssets;

// Logical names of the icon assets, in one place so the two consumers that
// inline the icon (the HTML report header and the dashboard header) cannot
// drift onto different files.
internal static class AssetNames {
    // 144x144 palette copy of the brand art, ~9 KB, generated by
    // scripts/gen-report-icon.py and embedded by the dashboard classlib.
    //
    // Both consumers base64-inline this and render it at 48px, so the bytes are
    // paid in full on every report send and every dashboard page load while
    // ~99% of a full-size master would never be visible. Using BrandMaster here
    // previously cost ~752 KB of a ~840 KB report and ~800 KB of base64 in every
    // dashboard HTML response. Keep any replacement small; ReportIconTests
    // enforces a ceiling.
    //
    // The file name is historical: the report header was the first consumer.
    public const string HeaderIcon = "report-icon.png";

    // 776x776 brand master, ~600 KB. The source of truth for the store listing,
    // the docs site and the companion launcher icons, all of which read
    // assets/plugin-icon.png from disk.
    //
    // NOT embedded in any assembly: it has no code consumer, and carrying it
    // cost ~600 KB in both the plugin DLL and the dashboard classlib that ships
    // with all three companion builds. EmbeddedWebAssets.ReadAsync will return
    // null for this name. Named here only so tests can assert it stays out and
    // so the next reader does not have to rediscover why.
    public const string BrandMaster = "plugin-icon.png";
}
